/**
 * Email delivery diagnostic.
 *
 * Login is gated behind an emailed OTP, so a mailer that cannot send takes down
 * sign-in for every account while the API itself looks healthy — the failure
 * surfaces only as a 5xx on /auth/login, well after the password was accepted.
 * This script exercises the exact same configuration the server uses and
 * reports where it breaks, so the cause does not have to be inferred.
 *
 *   node scripts/checkEmail.js                 # check configuration + SMTP login
 *   node scripts/checkEmail.js you@gmail.com   # ...and send a real test message
 *
 * Credentials are read from the environment and are never printed.
 */

require('dotenv').config();

const sendEmail = require('../src/utils/sendEmail');
const { describeEmailConfig, verifySmtpCredentials } = sendEmail;

const mask = (value) => {
  const text = String(value || '');
  if (!text) return '(not set)';
  return `set (${text.replace(/\s+/g, '').length} chars)`;
};

const run = async () => {
  console.log('── Configuration ──────────────────────────────────────────────');
  console.log(`NODE_ENV        : ${process.env.NODE_ENV || '(unset)'}`);
  console.log(`SMTP_HOST       : ${process.env.SMTP_HOST || '(not set)'}`);
  console.log(`SMTP_PORT       : ${process.env.SMTP_PORT || '(not set, defaults to 587)'}`);
  console.log(`SMTP_USER       : ${process.env.SMTP_USER || '(not set)'}`);
  console.log(`SMTP_PASS       : ${mask(process.env.SMTP_PASS)}`);
  console.log(`RESEND_API_KEY  : ${process.env.RESEND_API_KEY ? 'set' : '(not set)'}`);
  console.log(`RESEND_FROM     : ${process.env.RESEND_FROM || '(not set)'}`);
  console.log(`ADMIN_EMAIL     : ${process.env.ADMIN_EMAIL || '(not set)'}`);

  const { resendUsable, warnings } = describeEmailConfig();
  if (warnings.length) {
    console.log('\n── Warnings ───────────────────────────────────────────────────');
    warnings.forEach((warning) => console.log(`! ${warning}`));
  }

  console.log('\n── SMTP login ─────────────────────────────────────────────────');
  const smtp = await verifySmtpCredentials();

  if (smtp.ok) {
    console.log(`PASS  Authenticated as ${process.env.SMTP_USER}`);
  } else {
    console.log(`FAIL  ${smtp.reason}`);

    // By far the most common cause, and invisible to any presence check: an app
    // password is bound to the Google account that generated it.
    if (/535|invalid login|username and password not accepted/i.test(smtp.reason)) {
      console.log('\n      Gmail rejected these credentials. Usual causes:');
      console.log('      1. SMTP_PASS was generated by a DIFFERENT Google account than SMTP_USER.');
      console.log('         An app password only ever works with the mailbox that created it.');
      console.log('      2. The app password was revoked, or 2-Step Verification was turned off');
      console.log('         (which silently invalidates every app password on the account).');
      console.log('      3. A normal account password was used instead of a 16-character app password.');
      console.log(`\n      Fix: sign in as ${process.env.SMTP_USER || 'SMTP_USER'} → Google Account →`);
      console.log('      Security → 2-Step Verification → App passwords → generate a new one.');
    }
  }

  // Deliverability to ordinary users depends on a sender that actually works:
  // SMTP that truly authenticates, or Resend on a verified (non-test) domain.
  const canDeliver = smtp.ok || resendUsable;

  const recipient = process.argv[2];
  if (!recipient) {
    console.log('\n── Result ─────────────────────────────────────────────────────');
    if (canDeliver) {
      console.log('Configuration looks usable. Pass an address to send a real test message:');
      console.log('  node scripts/checkEmail.js you@example.com');
    } else {
      console.log('Email CANNOT be delivered to ordinary users.');
      console.log('Login will fail with a 503 for every account until this is fixed.');
      process.exitCode = 1;
    }
    return;
  }

  console.log(`\n── Sending test message to ${recipient} ───────────────────────`);
  try {
    await sendEmail({
      to: recipient,
      subject: 'Vidyarthi Mitra - email delivery test',
      html: '<p>If you are reading this, verification codes can reach this inbox.</p>',
    });
    console.log('PASS  Accepted by the provider.');
    console.log('      Check Spam and Promotions too — delivery is not the same as inbox placement.');
  } catch (error) {
    console.log(`FAIL  ${error.message}`);
    process.exitCode = 1;
  }
};

run().catch((error) => {
  console.error('Diagnostic failed to run:', error);
  process.exitCode = 1;
});
