const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');

dotenv.config({ path: path.join(__dirname, '../.env') });

const Exam = require('../src/models/Exam');

const examsData = [
  // National Exams
  {
    name: 'Common University Entrance Test',
    shortName: 'CUET UG',
    conductingBody: 'National Testing Agency (NTA)',
    examDate: new Date('2026-05-15'),
    registrationDeadline: new Date('2026-03-30'),
    eligibility: '10+2 from a recognized board with minimum 50% aggregate.',
    pattern: 'MCQs, Computer Based Test (CBT)',
    officialUrl: 'https://exams.nta.ac.in/CUET-UG/',
    category: 'others',
    scope: 'national',
    participatingUniversities: 250,
    highlights: ['Accepted by 250+ Central, State, and Private Universities', 'India\'s largest UG entrance exam', 'Syllabus based on Class 12 NCERT'],
    courses: ['B.A.', 'B.Sc.', 'B.Com.', 'B.Tech.', 'BBA', 'BCA', 'Integrated M.Sc.'],
  },
  {
    name: 'Joint Entrance Examination - Main',
    shortName: 'JEE Main',
    conductingBody: 'National Testing Agency (NTA)',
    examDate: new Date('2026-04-04'),
    registrationDeadline: new Date('2026-03-02'),
    eligibility: '10+2 with Physics, Chemistry, and Mathematics.',
    pattern: 'MCQs and Numerical Value questions, CBT',
    officialUrl: 'https://jeemain.nta.ac.in/',
    category: 'engineering',
    scope: 'national',
    participatingUniversities: 150,
    highlights: ['Gateway to NITs, IIITs, and CFTIs', 'Accepted by top private engineering colleges', 'Two sessions held per year'],
    courses: ['B.Tech.', 'B.E.', 'B.Arch.', 'B.Planning'],
  },
  {
    name: 'National Eligibility cum Entrance Test',
    shortName: 'NEET UG',
    conductingBody: 'National Testing Agency (NTA)',
    examDate: new Date('2026-05-03'),
    registrationDeadline: new Date('2026-03-09'),
    eligibility: '10+2 with Physics, Chemistry, Biology/Biotechnology and English.',
    pattern: '200 MCQs (attempt 180), Pen & Paper based',
    officialUrl: 'https://neet.nta.nic.in/',
    category: 'medical',
    scope: 'national',
    participatingUniversities: 600,
    highlights: ['Single entrance test for MBBS & BDS in India', 'Includes AIIMS and JIPMER admissions', 'Available in 13 languages'],
    courses: ['MBBS', 'BDS', 'BAMS', 'BHMS', 'BSMS', 'BUMS'],
  },
  // State Exams
  {
    name: 'Maharashtra Common Entrance Test',
    shortName: 'MHT CET',
    conductingBody: 'State Common Entrance Test Cell, Maharashtra',
    examDate: new Date('2026-05-02'),
    registrationDeadline: new Date('2026-03-01'),
    eligibility: '10+2 with Physics, Mathematics, and Chemistry/Biology with minimum 45% marks.',
    pattern: 'MCQs, CBT format, PCM & PCB groups',
    officialUrl: 'https://cetcell.mahacet.org/',
    category: 'engineering',
    scope: 'state',
    state: 'Maharashtra',
    participatingUniversities: 300,
    highlights: ['Premier state level engineering & pharmacy exam for Maharashtra', 'No negative marking', 'Highly popular for private & government institutes in MH'],
    courses: ['B.Tech.', 'B.E.', 'B.Pharm.', 'Pharm.D.'],
  },
  {
    name: 'Preeminent Education and Research Association Common Entrance Test',
    shortName: 'PERA CET',
    conductingBody: 'PERA India',
    examDate: new Date('2026-05-25'),
    registrationDeadline: new Date('2026-05-10'),
    eligibility: '10+2 or equivalent with minimum 45% (varies by course).',
    pattern: 'MCQs, No negative marking, 120 minutes',
    officialUrl: 'https://peraindia.in/',
    category: 'engineering',
    scope: 'state',
    state: 'Maharashtra',
    participatingUniversities: 15,
    highlights: ['Single window exam for top Private Universities in Maharashtra', 'No negative marking', 'Online proctored exam from home'],
    courses: ['B.Tech.', 'M.Tech.', 'MBA', 'MCA', 'B.Pharm.', 'M.Pharm.', 'BFA', 'MFA'],
  },
  {
    name: 'Consortium of Medical, Engineering and Dental Colleges of Karnataka',
    shortName: 'COMEDK UGET',
    conductingBody: 'COMEDK',
    examDate: new Date('2026-05-12'),
    registrationDeadline: new Date('2026-04-05'),
    eligibility: '10+2 with Physics, Chemistry, Maths and English with 45% marks.',
    pattern: '180 MCQs, 3 hours, No negative marking',
    officialUrl: 'https://www.comedk.org/',
    category: 'engineering',
    scope: 'state',
    state: 'Karnataka',
    participatingUniversities: 190,
    highlights: ['Gateway to 190+ top engineering colleges in Karnataka', 'Open to students from all over India', 'No negative marking'],
    courses: ['B.Tech.', 'B.E.', 'B.Arch.'],
  },
  {
    name: 'West Bengal Joint Entrance Examination',
    shortName: 'WBJEE',
    conductingBody: 'WBJEEB',
    examDate: new Date('2026-04-30'),
    registrationDeadline: new Date('2026-01-31'),
    eligibility: '10+2 with Physics, Mathematics, and Chemistry/Biotech.',
    pattern: 'MCQs, OMR based, Two papers (Maths and Physics+Chemistry)',
    officialUrl: 'https://wbjeeb.nic.in/',
    category: 'engineering',
    scope: 'state',
    state: 'West Bengal',
    participatingUniversities: 100,
    highlights: ['State-level engineering entrance', 'Accepted by top private and government colleges in WB'],
    courses: ['B.Tech.', 'B.Pharm.', 'B.Arch.'],
  },
  {
    name: 'Telangana State Engineering, Agriculture and Medical Common Entrance Test',
    shortName: 'TS EAMCET',
    conductingBody: 'JNTU Hyderabad on behalf of TSCHE',
    examDate: new Date('2026-05-07'),
    registrationDeadline: new Date('2026-04-06'),
    eligibility: '10+2 with Physics, Chemistry and Mathematics/Biology.',
    pattern: '160 MCQs, 3 hours, CBT format',
    officialUrl: 'https://tseamcet.nic.in/',
    category: 'engineering',
    scope: 'state',
    state: 'Telangana',
    participatingUniversities: 150,
    highlights: ['State-wide entrance test for engineering and pharmacy in Telangana', 'Computer-based objective test'],
    courses: ['B.Tech.', 'B.Pharm.', 'B.Sc. (Agriculture)'],
  },
  {
    name: 'Andhra Pradesh Engineering, Agriculture and Pharmacy Common Entrance Test',
    shortName: 'AP EAPCET',
    conductingBody: 'JNTU Anantapur on behalf of APSCHE',
    examDate: new Date('2026-05-15'),
    registrationDeadline: new Date('2026-04-12'),
    eligibility: '10+2 with Physics, Chemistry and Mathematics/Biology.',
    pattern: '160 MCQs, 3 hours, CBT format',
    officialUrl: 'https://cets.apsche.ap.gov.in/',
    category: 'engineering',
    scope: 'state',
    state: 'Andhra Pradesh',
    participatingUniversities: 180,
    highlights: ['State-wide entrance test for engineering and pharmacy in AP', 'Computer-based objective test'],
    courses: ['B.Tech.', 'B.Pharm.', 'B.Sc. (Agriculture)'],
  },
  {
    name: 'Gujarat Common Entrance Test',
    shortName: 'GUJCET',
    conductingBody: 'Gujarat Secondary and Higher Secondary Education Board',
    examDate: new Date('2026-04-02'),
    registrationDeadline: new Date('2026-01-25'),
    eligibility: '10+2 with Physics, Chemistry and Mathematics/Biology.',
    pattern: '120 MCQs, OMR based',
    officialUrl: 'https://gujcet.gseb.org/',
    category: 'engineering',
    scope: 'state',
    state: 'Gujarat',
    participatingUniversities: 120,
    highlights: ['State exam for engineering and pharmacy courses in Gujarat', 'Weightage counts in state merit rank'],
    courses: ['B.Tech.', 'B.E.', 'B.Pharm.'],
  },
  {
    name: 'Kerala Engineering Architecture Medical',
    shortName: 'KEAM',
    conductingBody: 'Commissioner for Entrance Examinations, Kerala',
    examDate: new Date('2026-06-01'),
    registrationDeadline: new Date('2026-04-10'),
    eligibility: '10+2 with Physics, Chemistry, and Mathematics with minimum 50% marks.',
    pattern: 'MCQs, Computer Based Test',
    officialUrl: 'https://cee.kerala.gov.in/',
    category: 'engineering',
    scope: 'state',
    state: 'Kerala',
    participatingUniversities: 150,
    highlights: ['State-level professional entrance test for Kerala', 'Weighted combinations of board and entrance marks'],
    courses: ['B.Tech.', 'B.Arch.', 'B.Pharm.'],
  },
  {
    name: 'Rajasthan Technical University Common Entrance Test',
    shortName: 'RUCET',
    conductingBody: 'Rajasthan Technical University',
    examDate: new Date('2026-05-18'),
    registrationDeadline: new Date('2026-04-20'),
    eligibility: '10+2 with Physics, Chemistry and Mathematics with minimum 45% marks.',
    pattern: 'MCQs, 150 questions, 3 hours',
    officialUrl: 'https://rtu.ac.in/',
    category: 'engineering',
    scope: 'state',
    state: 'Rajasthan',
    participatingUniversities: 80,
    highlights: ['Admissions to engineering and technology colleges in Rajasthan', 'Accepted by private and government colleges in the state'],
    courses: ['B.Tech.', 'B.E.', 'M.Tech.'],
  },
  {
    name: 'Punjab Common Entrance Test',
    shortName: 'PUNJAB CET',
    conductingBody: 'Punjab Technical University (IKG PTU)',
    examDate: new Date('2026-06-15'),
    registrationDeadline: new Date('2026-05-10'),
    eligibility: '10+2 with Physics, Chemistry and Mathematics with 45% marks.',
    pattern: 'MCQs, 150 questions, 3 hours, CBT',
    officialUrl: 'https://ptu.ac.in/',
    category: 'engineering',
    scope: 'state',
    state: 'Punjab',
    participatingUniversities: 90,
    highlights: ['State-level entrance for engineering and pharmacy in Punjab', 'Accepted by PTU-affiliated colleges'],
    courses: ['B.Tech.', 'B.Pharm.', 'MCA'],
  },
  {
    name: 'Delhi Common Entrance Test',
    shortName: 'Delhi CET',
    conductingBody: 'Board of Technical Education, Delhi',
    examDate: new Date('2026-06-10'),
    registrationDeadline: new Date('2026-05-05'),
    eligibility: '10th pass (for lateral entry to Polytechnic) or 10+2 for B.Tech.',
    pattern: 'MCQs, OMR based',
    officialUrl: 'https://www.delhi.gov.in/page/cet',
    category: 'engineering',
    scope: 'state',
    state: 'Delhi',
    participatingUniversities: 45,
    highlights: ['Gateway to Polytechnic and engineering institutions in Delhi', 'Conducted by Board of Technical Education Delhi'],
    courses: ['B.Tech.', 'Polytechnic Diploma'],
  },
  {
    name: 'Uttar Pradesh State Entrance Examination',
    shortName: 'UPSEE',
    conductingBody: 'Dr. A.P.J. Abdul Kalam Technical University (AKTU)',
    examDate: new Date('2026-06-22'),
    registrationDeadline: new Date('2026-05-18'),
    eligibility: '10+2 with Physics, Chemistry and Mathematics/Biology with 45% marks.',
    pattern: 'MCQs, 3 hours, CBT',
    officialUrl: 'https://upcet.nta.nic.in/',
    category: 'engineering',
    scope: 'state',
    state: 'Uttar Pradesh',
    participatingUniversities: 200,
    highlights: ['State entrance for AKTU-affiliated engineering and pharmacy colleges in UP', 'One of the largest state entrance exams in India'],
    courses: ['B.Tech.', 'B.Pharm.', 'MBA', 'MCA'],
  },
  {
    name: 'Tamil Nadu Engineering Admissions',
    shortName: 'TNEA',
    conductingBody: 'Anna University',
    examDate: new Date('2026-06-05'),
    registrationDeadline: new Date('2026-04-30'),
    eligibility: '10+2 with Physics, Chemistry and Mathematics with minimum 50% marks (PCM).',
    pattern: 'Merit-based (no separate exam), Counselling process',
    officialUrl: 'https://tnea.ac.in/',
    category: 'engineering',
    scope: 'state',
    state: 'Tamil Nadu',
    participatingUniversities: 450,
    highlights: ['No separate entrance exam — admissions based on 12th board merit', 'Covers 450+ engineering colleges in Tamil Nadu', 'Online counselling process'],
    courses: ['B.E.', 'B.Tech.', 'B.Arch.'],
  },
  {
    name: 'Madhya Pradesh Pre-Engineering Test',
    shortName: 'MP PET',
    conductingBody: 'Madhya Pradesh Professional Examination Board (MPPEB)',
    examDate: new Date('2026-05-28'),
    registrationDeadline: new Date('2026-04-22'),
    eligibility: '10+2 with Physics, Chemistry and Mathematics.',
    pattern: '150 MCQs, 3 hours, OMR based',
    officialUrl: 'https://www.mppeb.org/',
    category: 'engineering',
    scope: 'state',
    state: 'Madhya Pradesh',
    participatingUniversities: 120,
    highlights: ['State-level engineering entrance exam for Madhya Pradesh', 'Accepted by private and government engineering colleges in MP'],
    courses: ['B.E.', 'B.Tech.'],
  },
  {
    name: 'Jharkhand Combined Entrance Competitive Examination',
    shortName: 'JCECE',
    conductingBody: 'Jharkhand Combined Entrance Competitive Examination Board',
    examDate: new Date('2026-05-25'),
    registrationDeadline: new Date('2026-04-15'),
    eligibility: '10+2 with Physics, Chemistry and Mathematics/Biology.',
    pattern: '150 MCQs, 3 hours',
    officialUrl: 'https://jceceb.jharkhand.gov.in/',
    category: 'engineering',
    scope: 'state',
    state: 'Jharkhand',
    participatingUniversities: 50,
    highlights: ['State entrance exam for engineering, pharmacy, and agriculture in Jharkhand'],
    courses: ['B.Tech.', 'B.Pharm.', 'B.Sc. (Agriculture)'],
  },
  {
    name: 'Odisha Joint Entrance Examination',
    shortName: 'OJEE',
    conductingBody: 'Odisha Joint Entrance Examination Committee',
    examDate: new Date('2026-05-18'),
    registrationDeadline: new Date('2026-04-08'),
    eligibility: '10+2 with PCM/PCB with minimum 45% marks (for B.Tech lateral entry: 3-yr Diploma).',
    pattern: 'MCQs, OMR based, 3 hours',
    officialUrl: 'https://ojee.nic.in/',
    category: 'engineering',
    scope: 'state',
    state: 'Odisha',
    participatingUniversities: 80,
    highlights: ['State-level entrance exam for lateral entry and MBA/MCA/M.Tech in Odisha', 'Accepted by all BPUT-affiliated colleges'],
    courses: ['B.Tech. (Lateral Entry)', 'MBA', 'MCA', 'M.Tech.'],
  },
  {
    name: 'Bihar Combined Entrance Competitive Examination',
    shortName: 'BCECE',
    conductingBody: 'Bihar Combined Entrance Competitive Examination Board',
    examDate: new Date('2026-05-10'),
    registrationDeadline: new Date('2026-03-20'),
    eligibility: '10+2 with Physics, Chemistry and Mathematics/Biology with minimum 45%.',
    pattern: '50 questions per subject, OMR based',
    officialUrl: 'https://bceceboard.bihar.gov.in/',
    category: 'engineering',
    scope: 'state',
    state: 'Bihar',
    participatingUniversities: 60,
    highlights: ['State-level entrance for engineering, pharmacy, and agriculture in Bihar'],
    courses: ['B.Tech.', 'B.Pharm.', 'B.Sc. (Agriculture)'],
  },
  {
    name: 'Himachal Pradesh Combined Entrance Test',
    shortName: 'HP CET',
    conductingBody: 'Himachal Pradesh Technical University (HPTU)',
    examDate: new Date('2026-06-08'),
    registrationDeadline: new Date('2026-05-01'),
    eligibility: '10+2 with Physics, Chemistry and Mathematics with 45% marks.',
    pattern: 'MCQs, 2.5 hours, CBT',
    officialUrl: 'https://www.himtu.ac.in/',
    category: 'engineering',
    scope: 'state',
    state: 'Himachal Pradesh',
    participatingUniversities: 35,
    highlights: ['State entrance for HPTU-affiliated engineering and pharmacy colleges in HP'],
    courses: ['B.Tech.', 'B.Pharm.', 'MCA'],
  },
  // University Specific Exams
  {
    name: 'Birla Institute of Technology and Science Admission Test',
    shortName: 'BITSAT',
    conductingBody: 'BITS Pilani',
    examDate: new Date('2026-05-20'),
    registrationDeadline: new Date('2026-04-11'),
    eligibility: '10+2 with Physics, Chemistry, Mathematics (or Biology for B.Pharm) and English.',
    pattern: '130 MCQs, 3 hours, negative marking (+3/-1)',
    officialUrl: 'https://www.bitsadmission.com/',
    category: 'engineering',
    scope: 'university',
    participatingUniversities: 4, // Campuses
    highlights: ['Admission to BITS Pilani, Goa, Hyderabad, and Dubai campuses', 'Highly competitive exam', 'Direct admission for Board toppers'],
    courses: ['B.E.', 'B.Pharm.', 'M.Sc. (Integrated)'],
  },
  {
    name: 'Vellore Institute of Technology Engineering Entrance Examination',
    shortName: 'VITEEE',
    conductingBody: 'VIT University',
    examDate: new Date('2026-04-19'),
    registrationDeadline: new Date('2026-03-31'),
    eligibility: '10+2 with Physics, Chemistry, and Mathematics/Biology with 60% aggregate.',
    pattern: '125 MCQs, 2.5 hours, No negative marking',
    officialUrl: 'https://viteee.vit.ac.in/',
    category: 'engineering',
    scope: 'university',
    participatingUniversities: 4, // Campuses
    highlights: ['Admission to VIT Vellore, Chennai, AP, and Bhopal campuses', 'Multiple slots and dates available', 'Equated scoring system'],
    courses: ['B.Tech.'],
  },
  {
    name: 'SRM Joint Engineering Entrance Examination',
    shortName: 'SRMJEEE',
    conductingBody: 'SRM Institute of Science and Technology',
    examDate: new Date('2026-04-22'),
    registrationDeadline: new Date('2026-04-15'),
    eligibility: '10+2 with Physics, Chemistry, and Mathematics/Biology.',
    pattern: '125 MCQs, 2.5 hours, No negative marking',
    officialUrl: 'https://www.srmist.edu.in/',
    category: 'engineering',
    scope: 'university',
    participatingUniversities: 6, // Campuses
    highlights: ['Admission to SRM IST Chennai (Kattankulathur, Ramapuram, Vadapalani, Tiruchirappalli), Delhi-NCR, and AP campuses', 'Online remote proctored mode'],
    courses: ['B.Tech.', 'B.Arch.', 'M.Tech.'],
  }
];

async function seedExams() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Remove existing exams to avoid duplicates in this demo script
    await Exam.deleteMany({});
    
    await Exam.insertMany(examsData);
    console.log('Exams seeded successfully!');
    
    process.exit(0);
  } catch (error) {
    console.error('Error seeding exams:', error);
    process.exit(1);
  }
}

seedExams();
