// UGC List of Deemed to be Universities (as of 2026)
// Source: https://deemed.ugc.ac.in/Home/ListOfDeemedToBeUniversity
// Used for classifying universities that may be mislabeled in Excel files

const DEEMED_UNIVERSITIES = [
  'Academy of Maritime Education and Training',
  'Amrita Vishwa Vidyapeetham',
  'Audisankara',
  'Aurora Higher Education',
  'Avinashilingam Institute',
  'B.S. Abdur Rahman Institute',
  'Banasthali Vidyapith',
  'Bharath Institute of Higher Education',
  'Bharati Vidyapeeth',
  'Birla Institute of Technology',
  'Birla Institute of Technology & Science',
  'BITS Pilani',
  'BLDE',
  'Central Institute of Buddhist Studies',
  'Central Institute of Fisheries Education',
  'Central Institute of Higher Tibetan Studies',
  'Central Institute of Technology',
  'Chaitanya',
  'Chennai Mathematical Institute',
  'Chettinad Academy',
  'Chinmaya Vishwavidyapeeth',
  'Christ University',
  'D. Y. Patil',
  'DY Patil',
  'Datta Meghe Institute',
  'Dayalbagh Educational Institute',
  'Deccan College',
  'Defence Institute of Advanced Technology',
  'Dhanalakshmi Srinivasan Institute',
  'Dr. D.Y. Patil Vidyapeeth',
  'Dr. M.G.R. Educational',
  'Film and Television Institute of India',
  'Forest Research Institute',
  'GITAM',
  'Gandhigram Rural Institute',
  'Gokhale Institute',
  'Graphic Era',
  'Gujarat Vidyapith',
  'Gurukula Kangri',
  'Hindustan Institute of Technology',
  'Homi Bhabha National Institute',
  'ICFAI Foundation',
  'IIS University',
  'Indian Agricultural Research Institute',
  'Indian Association for the Cultivation of Science',
  'Indian Institute for Human Settlements',
  'Indian Institute of Foreign Trade',
  'Indian Institute of Forest Management',
  'Indian Institute of Heritage',
  'Indian Institute of Mass Communication',
  'Indian Institute of Science',
  'Indian Institute of Space Science and Technology',
  'Indian Law Institute',
  'Indian Veterinary Research Institute',
  'Indira Gandhi Institute of Development Research',
  'Institute of Advanced Studies in Education',
  'Institute of Chemical Technology',
  'Institute of Liver and Biliary Sciences',
  'International Institute for Population Sciences',
  'International Institute of Information Technology',
  'IIIT Bangalore',
  'IIIT Hyderabad',
  'JAIN University',
  'Jain Vishva Bharati Institute',
  'Jamia Hamdard',
  'Janardan Rai Nagar Rajasthan Vidyapeeth',
  'Jawaharlal Nehru Centre for Advanced Scientific Research',
  'Jaypee Institute of Information Technology',
  'JSS Academy of Higher Education',
  'Kalasalingam Academy',
  'Kalinga Institute of Industrial Technology',
  'KIIT',
  'Kalinga Institute of Social Sciences',
  'KISS',
  'Karpaga Vinayaga',
  'Karpagam Academy',
  'Karunya Institute of Technology',
  'Kerala Kalamandalam',
  'KLE Academy',
  'Koneru Lakshmaiah Education Foundation',
  'KL University',
  'Krishna Vishwa Vidyapeeth',
  'Kristu Jayanti',
  'Lakshmibai National Institute',
  'Lingaya\'s Vidyapeeth',
  'Madanapalle Institute',
  'Madhav Institute of Technology',
  'Maharishi Markandeshwar',
  'Malla Reddy',
  'Manav Rachna International Institute',
  'Manipal Academy of Higher Education',
  'MAHE',
  'Meenakshi Academy',
  'MGM Institute of Health Sciences',
  'Morarji Desai National Institute',
  'Narsee Monjee Institute',
  'NMIMS',
  'National Brain Research Centre',
  'National Dairy Research Institute',
  'National Institute of Advanced Manufacturing',
  'NIAMT',
  'National Institute of Ayurveda',
  'National Institute of Educational Planning',
  'NIEPA',
  'National Institute of Technical Teachers Training',
  'NITTTR',
  'Nava Nalanda Mahavihara',
  'Nehru Gram Bharati',
  'Netaji Subhash Chandra Bose Institute',
  'NITTE',
  'Noorul Islam Centre',
  'North Eastern Regional Institute',
  'NERIST',
  'Periyar Maniammai Institute',
  'Ponnaiyah Ramajayam Institute',
  'PMIST',
  'Pravara Institute of Medical Sciences',
  'Prestige Institute',
  'Punjab Engineering College',
  'Ramakrishna Mission Vivekananda',
  'SRM Institute of Science and Technology',
  'SRM',
  'Sam Higginbottom Institute',
  'Sant Longowal Institute',
  'SLIET',
  'Santosh University',
  'Sathyabama Institute',
  'Satyajit Ray Film Institute',
  'Saveetha Institute',
  'SASTRA',
  'Shobhit Institute',
  'Siddhartha Academy',
  'Siksha O Anusandhan',
  'SOA',
  'Sir J.J School of Art',
  'Sri Balaji Vidyapeeth',
  'Sri Chandrasekharandra Saraswati',
  'Sri Devaraj Urs Academy',
  'Sri Krishna Knowledge Foundation',
  'Sri Ramachandra Institute',
  'Sri Sathya Sai Institute',
  'Sri Siddhartha Academy',
  'St. Aloysius',
  'St. Peter\'s Institute',
  'Sumandeep Vidyapeeth',
  'Swami Vivekananda Yoga',
  'S-VYASA',
  'Symbiosis International',
  'Tata Institute of Fundamental Research',
  'TIFR',
  'Tata Institute of Social Sciences',
  'TISS',
  'TCG CREST',
  'TERI School',
  'Thapar Institute of Engineering',
  'LNM Institute',
  'LNMIIT',
  'Tilak Maharashtra Vidyapeeth',
  'Vel Tech Rangarajan',
  'Vellore Institute of Technology',
  'VIT',
  'Vels Institute',
  'VISTAS',
  'Vignan\'s Foundation',
  'Vinayaka Mission',
  'Yenepoya',
];

module.exports = { DEEMED_UNIVERSITIES };
